codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "70...90"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  - "sporco/tests"
  - "sporco/admm/tests"
  - "sporco/fista/tests"
  - "test_*.py"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

