# When a tag is pushed, build packages and upload to PyPI

name: pypi

# Trigger when tags are pushed
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-and-upload:
    name: Upload package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda config --env --append channels conda-forge
          $CONDA/bin/conda env update --file requirements.txt --name base
          $CONDA/bin/python -m pip install --upgrade pip
          $CONDA/bin/pip install wheel
          $CONDA/bin/python setup.py sdist bdist_wheel
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
